name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [labeled] #, opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned

jobs:
  updateAzDO:
    if: github.event.label.name == 'sprint'
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "devdiv"
          ado_project: "DevDiv"
          ado_area_path: "DevDiv\\NET Developer Experience\\Testing Platforms\\TestPlatform"
          ado_iteration_path: "DevDiv\\OneVS\\Cobalt [Co]\\Q1\\Sprint 182"
          ado_wit: "User Story"
          ado_new_state: "Committed"
          ado_active_state: "In Progress"
          ado_close_state: "Completed"
          ado_bypassrules: false
